### ISSUE TITLE
Merge api server and webhook handler server

### ISSUE THREAD

**Issue by umurgdk** [mobingilabs/pullr#7]
There is no benefit to keep them separate right now. It just adds complexity.

**Comment by umurgdk** [comment]
@flowerinthenight I'm going to use Host header for register webhook url on github as well as oauth redirect url. Do you think that cause security flaw?

**Comment by flowerinthenight** [comment]
@umurgdk This is still for the open source version, right? I'm not an expert in security (far from it) so I have no idea. But please proceed for now. If somebody will use it later on, we will expect some comments by then if there is actually an issue with security.

**Comment by umurgdk** [comment]
Actually I’ve implemented with via configuration before with separate webhook url and oauth redirect whitelists and etc. But it makes the configuration more difficult for deployments. So i’ve changed into request headers for now.

Thanks,
Umur Gedik
